apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-database
  template:
    metadata:
      labels:
        app: my-database
    spec:
      containers:
        - name: my-database
          image: mysql-server:5.7
          ports:
            - containerPort: 3306
      imagePullSecrets:
        - name: my-registry-secret
