apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-application
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-application
  template:
    metadata:
      labels:
        app: my-application
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:latest
          command: ['sh', '-c', 'until nslookup my-database; do echo waiting for db; sleep 2; done;']
      containers:
        - name: my-application
          image: busybox:latest
          ports:
            - containerPort: 8090
          env:
            - name: DB_HOST
              value: my-database
      imagePullSecrets:
        - name: my-registry-secret
