apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache
          image: httpd:latest
          ports:
            - containerPort: 80
            env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: secret-key
          #volumeMounts:
            #- name: config
             # mountPath: /usr/local/apache2/conf/httpd.conf
              #subPath: httpd.conf
      #volumes:
       # - name: config
        #  configMap:
         #   name: apache-config
